serviceAccount:
  create: true
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::687398153695:role/cloudhero-staging-irsa

# Optional: controller config
installCRDs: true
