services:
  ansible:
    image: cytopia/ansible:2.13-tools-manifest-linux-amd64
    container_name: ansible_runner
    working_dir: /ansible
    stdin_open: true
    tty: true
    volumes:
      - ./:/ansible
      - ./.ssh-keys/:/root/.ssh

      
